### ISSUE TITLE
'umbrel app create' funktioniert im Community Appstore nicht 

### ISSUE THREAD

**Issue by tgru-dev** [sharknoon/umbrel-cli#3]
Hey da du anscheinend aus Deutschland bist schreib ich das ganze mal auf Deutsch 😅

Beim Community Appstore funktioniert das App erstellen nicht bzw. der Appstore wird nicht erkannt. 

<img width="693" alt="Bildschirmfoto 2024-07-03 um 17 25 19" src="https://github.com/sharknoon/umbrel-cli/assets/97314280/8095b0b9-3c54-49a6-b7fa-a2321140663f">

Das ist der Error der immer angezeigt wird. Will auch dazu sagen das im offiziellen Appstore alles funktioniert.

**Comment by sharknoon** [comment]
Hi @tgru-dev, ich schaue es mir gerade an, danke für das Issue

**Comment by sharknoon** [comment]
Ich kann den Fehler nicht reproduzieren. Bist du im Root Verzeichnis des Repositories (also im gleichen Verzeichnis wie die `umbrel-app-store.yml`)? Ansonsten kannst du mal updaten probieren (`npm update -g umbrel-cli`)

**Comment by tgru-dev** [comment]
also ich bin im Root Verzeichnis und hab grad umbrel-cli und npm geupdated  immer noch der Fehler.
Bin auch auf MacOS vlt hat das was damit zu tun wobei ich das eher weniger glaube

**Comment by sharknoon** [comment]
Oh kann das sein, dass noch keine App im App Store ist? Dann habe ich den Fehler nämlich gefunden

**Comment by sharknoon** [comment]
Ich hab gerade eine neue Version veröffentlicht. Bitte update die Umbrel CLI mit `npm update -g umbrel-cli`, prüfe mit `umbrel-cli -v`, ob die Version `0.3.4` ist und prüfe, ob der Fehler behoben ist. Ich danke dir 😀

**Comment by tgru-dev** [comment]
Funktioniert wunderbar 👍
